services:
  frappe:
    ports: !override
      - "8088:8000"
    environment:
      - FRAPPE_SITE_URL=http://localhost:8088
    volumes:
      - ./docker-start.sh:/docker-start.sh:ro
    command: bash /docker-start.sh
